### ISSUE TITLE
Update to Jakarta EE8 APIs for MP 3.3 in Feb 2020

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-graphql#103]

**Comment by andymc12** [comment]
@WhiteCat22 is planning to work on this (I cannot assign it to him...).

I made a similar change in the MP Rest Client in https://github.com/eclipse/microprofile-rest-client/pull/233

**Comment by WhiteCat22** [comment]
Planning to take a look at this when I free up

**Comment by kenfinnigan** [comment]
Not sure if this needs to be re-opened now that Jakarta update has been pushed to MP 4.0 in June

**Comment by andymc12** [comment]
We should be fine to leave this issue closed since this project has not had any public GA releases yet (so we will use Jakarta dependencies right out the gate).
