### ISSUE TITLE
Naming Emun

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#104]
Can we name a Enum ? `@Name` ? Or can we have `@InputType` `@Type` ?

**Comment by phillip-kruger** [comment]
We also discussed mapping directly to the name in the schema. So `@Input` `@Type` and `@Enum`

**Comment by andymc12** [comment]
I think `@Name` for sure should be honored for enum types.  I'm not sure if we need a new `@Enum` annotation though... what do others think?

**Comment by phillip-kruger** [comment]
Let's discuss today. Also changing InputType to Input. So then we match the schema

**Comment by phillip-kruger** [comment]
Consensus is to create new @Enum annotation (name from it’s value is used for the schema name of the enum) - if no name in @Enum annotation, then use name from @Name (if there, and if non-empty), then use the Java enum name.
Consensus is to rename @InputType to @Input
