### ISSUE TITLE
TCK: Unassociated `@Type` and `@Input` should implement an associated `@Interface`

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-graphql#125]
The TCK should be updated so that types and input types (and enums referenced by them) that are not reachable by the top-level queries and mutations should implement interfaces that are reachable by the top-level queries/mutations.

If types and input types are not reachable from top-level operations and do not implement interfaces that are reachable, then they should not be listed in the schema as they are not usable.

**Comment by phillip-kruger** [comment]
Hi @andymc12 - Can we close this one ?

**Comment by andymc12** [comment]
Yes, thanks!
