### ISSUE TITLE
Support for all java.time classes.

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#142]
At the moment we only support LocalDate, LocalDateTime and LocalTime. Add support for all time objects in the java.time api. (for scalars). This should include spec and tck enhancements

**Comment by phillip-kruger** [comment]
From this list: https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html

What should we support ?

**Comment by andymc12** [comment]
Per discussion on today's call, we decided that we should try to support `ZonedDateTime`, `OffsetDateTime` and `OffsetTime` if possible.  If it is not convenient, then we can defer this issue to 1.1 and just use `LocalDate`, `LocalDateTime` and `LocalTime` for 1.0.
