### ISSUE TITLE
Get the superhero application running in Arquillian

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#15]
As per the high level diagram, we need a application to test against, that can run in Arquillian.

**Comment by jefrajames** [comment]
Application available on GitHub: https://github.com/jefrajames/mpql-run. Enables to run any MicroProfile Application (such as SuperHero) to run in any Java EE 8 platform (such as GlassFish). Also tested on Payara and OpenLiberty. Everything is in the README.

**Comment by phillip-kruger** [comment]
Awesome, I'll look at this a.s.a.p. Thanks

**Comment by phillip-kruger** [comment]
Done in #27
