### ISSUE TITLE
Feedback to 1.0.0-RC1

### ISSUE THREAD

**Issue by andimarek** [eclipse/microprofile-graphql#167]
Hi,

some general feedback to version 1.0.0-RC1:

1. I would highly recommend to drop the requirement to support the Short, Long, Byte, Char, BigInteger, BigDecimal custom scalars. These are very Java specific and clients/tooling can't deal with them in any meaningful way.

2. Date, Time, DateTime are definitely more useful but I would recommend to specify them via [specification url](https://github.com/graphql/graphql-spec/pull/649). The hope is that the graphql ecosystem will agree on some Date related scalars clearly specified by a spec. 

3. Nullable should always be the default for fields, even for primitives. Making a field non nullable has quite a few consequences and should always be a very conscious and explicit decision.

4. Mapping the `DataFetchingEnvironment` and the possible return values is a big challenge: for example in order to use Batched loading efficiently you have to return `CompletableFuture`. Also returning Errors and Data is a very valid use case. See https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/DataFetcherResult.java. There are also numerous other things inside `DataFetchingEnvironment` which are essential for writing production ready resolves.

A general question I have is how you see the relationship between this spec and GraphQL Java: Should this spec never reference GraphQL Java specific and therefore be always be "abstract" or is it possible to say for example: you can pass down a `DataFetchingEnvironment` to allow access to all features. 

Thanks,
Andi

**Comment by phillip-kruger** [comment]
Hi @andimarek 

Thanks very much for the feedback.

1) Ok we have been looking at this from a Java perspective, however we should still be able to support the Java types (on the Java side) but map them to Int, Float, String respectively.

2) Great. Would `@specified` apply to any custom scalar ? We have been adding the date specification in the description (we can keep that there) but we should be able to add `@specified` as well. This might be something that we add in v1.1 ?

3) I think we also looked at this one from a Java point of view. As a primitive in Java can not be null. Not sure how we could handle the implementation in case of a null primitive (on the Java side)? At least for input type. For output we should be able to support it.

4) So a DataFetchingEnvironment feature is also on the feature list for v.1.1 (see https://github.com/eclipse/microprofile-graphql/issues/127), we can not expose graphql-java objects in the API (else we tie the implementation to the spec - even though at the moment both implementations, SPQR and SmallRye, is build on graphql-java). So the plan would be to have a similar object that can be injected anywhere and used as the user needs. We have not fleshed this out yet, but this is highest priority when we start with v.1.1 - any assistance/guidance will be appreciated !

@andymc12, @kaqqao, @thejibz, @WhiteCat22, @jefrajames please add your comments.

@andimarek - Thanks again for taking the time to give us feedback. Appreciate it. You are also most welcome to join our weekly meeting or join us on gitter.

**Comment by andymc12** [comment]
@andimarek I agree with Phillip - many thanks for the feedback.  We have discussed most of these issues in our weekly meetings and in gitter ( https://gitter.im/eclipse/microprofile-graphql ).

1. I tend to agree that we should use the existing scalars for most of the Java numerical keywords (float, short, long, etc.).  One reason to the contrary would be the limitations of the scalars.  For example, the GraphQL Int scalar says it is a 32-bit integer.  That would cover Java primitives like short, int, and byte, but it is too small to handle long or BigInteger types.  
2. +1 - and I agree with Phillip that this should be included in MP GraphQL 1.1.
3. I agree with Phillip's response here too.  I think we have language in the specification document that recommends using the non-primitive type (`Integer` as opposed to `int`) in order to allow nulls.  In the output case, the only way that I can think of to actually return a null value for a GraphQL query/mutation when the Java return type is a primitive would be to throw an exception. I prefer the existing behavior wrt to primitives (especially on input types) as "null" definitely has a different meaning than "-1" or "0", etc.
4. +1 - I also think this should be a high priority issue for 1.1.  

Wrt to explicitly depending on graphql-java, my preference is that we should not as that allows vendor implementations more freedom.  That said (and as Phillip mentioned), most implementations will most likely build on graphql-java.

Thanks again!

**Comment by andimarek** [comment]
One fundamental challenges you are facing with the whole approach to define your schema via Java types is that you mix implementation with exposed GraphQL API  (by design, that is the whole point, right?).

Using Java types for custom scalars is a good example: it is perfectly fine to use BigInteger in your Java code, but at the end you have to think how to expose this data to the client (or how to receive it). You are not creating a Java API but a GraphQL API and the GraphQL ecosystem doesn't have a good support for custom scalars at the moment. (Like I said that this will hopefully change in the future with the specification url, but we are not there yet).

A BigInteger for example is probably best mapped to a String at a moment together with a description on field saying it is an unlimited number.

The ideal state in the future would be that there is a custom scalar with a spec which is semantically equal to a BigInteger and which is supported by other clients/tools.

Imho you should define to what scalars certain java types are mapped and probably recommend some description on the fields. The current GraphQL scalars you can currently map to in a meaningful way are only the built-in ones and to some extend  DateTime, URL and maybe a few others. (I say that very hesitant, because even DateTime is not really safe to map to because the different DataTime implementations vary in detail)

I created the Java custom scalars which come from Java types (Short, BigInteger etc) in the beginning because I didn't know better at this time, but they should almost never be used. (And we are actually removing them from GraphQL Java in the next release).

**Comment by phillip-kruger** [comment]
Hi @andimarek . Thanks for the reply.

So how about this:

- We limit the number of custom scalars, only supporting extra Big* for larger numbers. We map the others to existing GraphQL Types.
- We make sure to add a warning in the spec about the limited support in client tools with those custom scalars. 
- We mention the upcoming support for `@specified` and once that is available we add that to the Big* custom scalars.
- Optionally we add a new annotation, something like `@MapTo` that allows a user to define a scalar that a certain type should map to (limited to existing scalars). So in the case of BigDecimal that a user rather wants to map to String, that can be done something like `@MapTo(STRING)`

@andimarek how does that sound ?

@andymc12, @kaqqao, @thejibz, @WhiteCat22, @jefrajames please add your comments.

**Comment by kaqqao** [comment]
I agree with pretty much everything being said here.

Just one remark on the return values and `DataFetchingEnvironment`. I don't personally find it too troublesome to deal with those. Return types are limited to raw types, `CompletableFuture`, `Publisher` and `DataFetchingResult`. All have clear semantics and can be mapped transparently (been doing that in SPQR). For partial results (`DataFetchingResult`) we already have decent support via a special exception.

As for the environment, I'd suggest an approach similar to SPQR's: expose the most useful values directly via a new implementation-agnostic interface and enable reaching the lower API as needed (i.e. leaky abstraction). This is very similar to what JAX-RS or even JPA do as well: provide a standard interface that can be _unwrapped_ to reach the underlying one.
E.g. `EntityManager` can be unwrapped into e.g. Hibernate's `Session`.

**Comment by phillip-kruger** [comment]
@kaqqao - cool thanks. So the DataFetchingEnviroment is on the TODO for v1.1 and we can flesh that out then.

W.r.t v1.0, do you think we should add a `@MapTo` annotation ?

**Comment by phillip-kruger** [comment]
@andimarek @andymc12 @kaqqao :

**Point 1:**
Please see [this PR](https://github.com/eclipse/microprofile-graphql/pull/168/commits/f455190609692e215e5541ca540069fac1a9ac6b)

That should solve point 1. I think the `@MapTo` suggestion can wait for 1.1 (if ever ?)?

**Point 2:** Added #169 to look at this.

**Point 3:** Please see [this PR](https://github.com/eclipse/microprofile-graphql/pull/168/commits/17612aa7f950b3518352346c6a6ecbe9125fde5b)

**Point 4:** Covered in #127 , Added @andimarek comment from here.
