### ISSUE TITLE
Clarify Scalar-to-Java type mappings

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-graphql#18]
See: https://github.com/eclipse/microprofile-graphql/blob/master/spec/src/main/asciidoc/entities.asciidoc#scalars

This should include spec text indicating how the built-in scalars should be mapped to Java types (i.e. "Int" to "int" and "Integer", "String" to "String", etc.).  This should also include TCK tests that verify that scalars are correctly mapped to the appropriate Java types.

More background information here:  https://graphql.org/learn/schema/#scalar-types

Custom scalar types should not be addressed with this issue. That should be addressed in a separate issue.

**Comment by phillip-kruger** [comment]
Thanks !
