### ISSUE TITLE
Structure of the client

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#181]
Should the client be 

part of this spec
part of this spec project but a separate module(s)
a new microprofile spec.

Possible layouts could be:

**Old Parent**
* Api
* Spec
* TCK

**New Parent**
Server (Old Parent)
* Api
* Spec
* TCK

Client
* Api
* Spec
* TCK

We need to take this to the communicate to get feedback

**Comment by andymc12** [comment]
I posted the question to the MP community here:
https://groups.google.com/forum/#!topic/microprofile/_6joz7OOvuw

**Comment by phillip-kruger** [comment]
Thanks @andymc12 . I am closing this, we can record the feedback from the community in #96
