### ISSUE TITLE
Inconsistencies in generated schema for Description annotation

### ISSUE THREAD

**Issue by tmiddlet2666** [eclipse/microprofile-graphql#183]
In some places in the Javadoc for `@Description` is generated with a comment prefix of `#` see - https://download.eclipse.org/microprofile/microprofile-graphql-1.0/apidocs/org/eclipse/microprofile/graphql/Description.html 

In the spec it says the generated descriptions are enclosed in Quotes? -  https://download.eclipse.org/microprofile/microprofile-graphql-1.0/microprofile-graphql.html#description

The GraphQL Spec says comments are only # - http://spec.graphql.org/June2018/#sec-Comments

**Comment by phillip-kruger** [comment]
Thanks @tmiddlet2666. Good catch ! I'll fix the spec, Description should be `"` and comments `#`
