### ISSUE TITLE
@Comment annotation

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#187]
As discusses with @tmiddlet2666 and in the meeting today - let's add a `@Comment` annotation to allow users to add comments to the schema ?

@kaqqao - you thoughts ?

**Comment by kaqqao** [comment]
As far as I know, there's no API in graphql-java for that 🤨

**Comment by phillip-kruger** [comment]
O yes, I remember now, they only have Description right ? So maybe we should first add the issue there. 
Do you think we need it ?

**Comment by kaqqao** [comment]
Sounds legit, I think. Since comments only make sense in the SDL, maybe a simple extension to the `SchemaPrinter` is all that's needed...

**Comment by phillip-kruger** [comment]
thanks @kaqqao !

**Comment by phillip-kruger** [comment]
Closing for now (graphql-java does not have this)
Maybe add a ticket/PR for graphql-java ?

**Comment by tmiddlet2666** [comment]
thanks @phillip-kruger see - https://github.com/graphql-java/graphql-java/issues/1848
