### ISSUE TITLE
Clarification of Source annotation example

### ISSUE THREAD

**Issue by tmiddlet2666** [eclipse/microprofile-graphql#196]
In the spec (https://download.eclipse.org/microprofile/microprofile-graphql-1.0/microprofile-graphql.html#fields )
 
It shows that a Location object is returned from 
```   
public Location currentLocation(@Source SuperHero hero) {
        return getLocationForHero(hero.getName());
    }
```
and it generates

```
type SuperHero {     
...
   currentLocation: String     
... 
```

The generated schema shows currentLocation returning String but the method returns Location.

Which one is correct as I assume the method should return String.

**Comment by phillip-kruger** [comment]
Thanks @tmiddlet2666 . Yes this is a bug, this should either be both Location or both String. I think in our TCK app we used String, so I'll update to String.

Thanks for reporting.
