### ISSUE TITLE
Additional clarification required in spec for number formatting

### ISSUE THREAD

**Issue by tmiddlet2666** [eclipse/microprofile-graphql#197]
In the spec, the section related to number formatting (https://download.eclipse.org/microprofile/microprofile-graphql-1.0/microprofile-graphql.html#_numbers)  shows examples of the JsonbNumberFormat and NumberFormat annotations being applied to member variables and method parameters.

The spec needs to clarify if these also apply to method return types as well.

If so, then there should be tests in the TCK to validate.

**Comment by phillip-kruger** [comment]
Thanks @tmiddlet2666. I'll see if I can get this done as part of 1.0.1

**Comment by phillip-kruger** [comment]
@tmiddlet2666 please see PR #198 and let me know. Thanks
