### ISSUE TITLE
Content-type in SchemaDynamicValidityTest.getSchemaContent is incorrect

### ISSUE THREAD

**Issue by tmiddlet2666** [eclipse/microprofile-graphql#202]
SchemaDynamicValidityTest.getSchemaContent contains the following
     
`connection.setRequestProperty("Content-Type", "plain/text");`

This should be "text/plain".

Perhaps the spec (https://download.eclipse.org/microprofile/microprofile-graphql-1.0.1/microprofile-graphql.html#_generated_schema)  indicate the content-type of the GET request or just leave it off completley.

https://github.com/eclipse/microprofile-graphql/blob/eccc1ab4de40165b550a1ba2af39596fcee391ee/server/tck/src/main/java/org/eclipse/microprofile/graphql/tck/dynamic/SchemaDynamicValidityTest.java#L127

**Comment by phillip-kruger** [comment]
Thanks @tmiddlet2666. I'll add to the 1.1 roadmap and maybe if there is enough other small issues we can do a 1.0.2
