### ISSUE TITLE
NPE while implementing java.io.Serializable

### ISSUE THREAD

**Issue by paschm** [eclipse/microprofile-graphql#206]
[modifed_graphql-example-master.zip](https://github.com/eclipse/microprofile-graphql/files/4403205/modifed_graphql-example-master.zip)
[stacktrace.txt](https://github.com/eclipse/microprofile-graphql/files/4403206/stacktrace.txt)

Implementing java.io.Serializable in a bean used in the GraphQL-schema leads to

java.lang.NullPointerException
	at deployment.person-example-1.0.0-SNAPSHOT.war//io.smallrye.graphql.schema.type.OutputTypeCreator.createInterface(OutputTypeCreator.java:166)
	
Attached you find the full stacktrace and a modified graphql-example-project for reproduction. There I changed com.github.phillipkruger.user.Person, so that it implements java.io.Serializable.

Thank you very much.

**Comment by phillip-kruger** [comment]
Hi @paschm .

Thanks for logging this, please can you log this in SmallRye: https://github.com/smallrye/smallrye-graphql/issues

Thanks :)

**Comment by paschm** [comment]
Hello @phillip-kruger,
of course this would be better than an issue for the spec. Sorry.

**Comment by paschm** [comment]
Issue in SmallRye created: smallrye/smallrye-graphql#94
