### ISSUE TITLE
Problem with Hibernate PersistentSet

### ISSUE THREAD

**Issue by paschm** [eclipse/microprofile-graphql#207]
I am using JPA with Hibernate implementation to persist my beans. I am using the same beans in the GraphQL-API. In one of these beans I have a OneToMany-mapping to a Set

```
	@OneToMany
	@JoinColumn(name = "konzernId")
	private Set<Gesellschaft> gesellschaften;
```

If I load these beans at runtime this will be a org.hibernate.collection.internal.PersistentSet. When serializing the GraphQL implementation creates a new instance of the PersistentSet in 

io.smallrye.graphql.execution.datafetcher.AnnotatedPropertyDataFetcher.get(AnnotatedPropertyDataFetcher.java:73)

and copies the elements of the previous PersistentSet in

io.smallrye.graphql.execution.datafetcher.AnnotatedPropertyDataFetcher.get(AnnotatedPropertyDataFetcher.java:75).

However this leads to a

org.hibernate.LazyInitializationException: failed to lazily initialize a collection, could not initialize proxy - no Session
	...
	at org.hibernate@5.3.13.Final//org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:581)
	at org.hibernate@5.3.13.Final//org.hibernate.collection.internal.PersistentSet.add(PersistentSet.java:210)

as the session is already and correctly closed at this position.

If the elemtens of the PersistentSet must be copied to a new Set maybe it would be possible to use a new instance of HashSet instead of PersistentSet? As it seems the used Collection-type is determined in

CollectionHelper.getCorrectCollectionType(Class)

Thank you very much.

**Comment by phillip-kruger** [comment]
Hi @paschm - Thanks for logging this.
I am going to close this one, can you please log the same in SmallRye: https://github.com/smallrye/smallrye-graphql/issues

Thanks

**Comment by paschm** [comment]
Hello @phillip-kruger,
of course this would be better than an issue for the spec. Sorry.

**Comment by paschm** [comment]
Issue in SmallRye created: https://github.com/smallrye/smallrye-graphql/issues/95
