### ISSUE TITLE
NonNull annotation should support ElementType.PARAMETER target

### ISSUE THREAD

**Issue by tmiddlet2666** [eclipse/microprofile-graphql#212]
Currently the NonNull annotation supports the following targets:
```
@Target({ElementType.TYPE_USE, ElementType.METHOD, ElementType.FIELD})
```

This means we are not able to do the following to specify that the `param` should be non null if we wanted to, as the default would be that it is nullable.

```
public String myMethod(@NonNull String param) {
...
```

Tests should also be added to check this.

**Comment by kaqqao** [comment]
Your example should actually work because of `ElementType.TYPE_USE`. The annotation applies to the `String` type itself in this case.
To achieve what we need, `ElementType.TYPE_USE` is the only necessary location. The others are redundant. So I suggest we either remove them or add `ElementType.PARAMETER` for consistency.

**Comment by andymc12** [comment]
I'm in favor of removing the other types.  But it sounds like we should also add a test case for `@NonNull` on a method parameter for completeness.

**Comment by tmiddlet2666** [comment]
@kaqqao Yes is see your point regarding

> The constant TYPE_USE corresponds to the 15 type contexts in JLS 4.11, as well as to two declaration contexts: type declarations (including annotation type declarations) and type parameter declarations.

Test case would be good then to confirm.
Thanks

**Comment by phillip-kruger** [comment]
@tmiddlet2666 will you do the change and add the test cases ?

**Comment by tmiddlet2666** [comment]
ok sure @phillip-kruger - I'll schedule for next week. master?

**Comment by phillip-kruger** [comment]
Thanks :) Yes master should be fine. Except if we think this should go into a 1.0.x ?

**Comment by t1** [comment]
I just was surprised to learned that this does make a difference for reflection: you can place the `@NonNull` annotation on a parameter, but the `Parameter#getAnnotation...` methods won't reflect the annotation until it's also targeted for `PARAMETER`.

Otherwise we can close this issue, can't we?

**Comment by tmiddlet2666** [comment]
Sorry @t1  this slipped through the cracks...
Should be ok to close.

**Comment by tmiddlet2666** [comment]
@t1 @phillip-kruger 
I think we need to re-open this as looking back it is still an issue.  (I did originally should be ok to close, but i didn't realise the ramification) 
Without the PARAMETER target, the @NonNull annotation cant' be discovered via reflection as @t1 mentioned above.
This means we can't use NonNull in a parameter to make a query or mutation mandatory.
The following shows this is the case. 
```
public class AnnotationTest {
    public static void main(String[] args) throws NoSuchMethodException {
        Method       method              = AnnotationTest.class.getMethod("myMethod", String.class);
        Parameter    parameter           = method.getParameters()[0];
        Annotation[] declaredAnnotations = parameter.getDeclaredAnnotations();
        Arrays.stream(declaredAnnotations).forEach(a ->System.out.println(a.annotationType().getName()));
    }

    public String myMethod(@NonNullTest @NonNullTest2  String param) {
        return param;
    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target( {ElementType.TYPE_USE, ElementType.METHOD, ElementType.FIELD})
    public static @interface NonNullTest {
    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target( {ElementType.TYPE_USE, ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER})
    public static @interface NonNullTest2 {
    }
}
```

I think we should add PARAMETER to NonNull annotation in master and backport or create a test  -> 1.0.x-service.

Thoughts?

**Comment by phillip-kruger** [comment]
Hi @tmiddlet2666 - I am reopening ! Thanks !

**Comment by t1** [comment]
I'm in favor of adding it, as it's semantically more clear: this annotation can go on a parameter. Period. That the `TYPE_USE` target allows it to be placed there technically, is just a side effect: although it may be intentional, it's not very obvious.

Maybe we could release this together with #348?

**Comment by kaqqao** [comment]
I'd either add `PARAMETER` or remove everything but `TYPE_USE`, to minimize surprises and implementation inconsistencies. Although having it everywhere makes implementation more difficult (annotations have to be merged beforehand).


> this annotation can go on a parameter. Period. That the `TYPE_USE` target allows it to be placed there technically, is just a side effect:

I'd actually claim the opposite 🙃 The annotation _really_ applies to the type, as e.g. a _nullable list of non nullable strings_ (`List<@NonNull String>`) is a perfectly valid parameter type, so it's not the parameter but the type itself that nullability applies to. Having it in both places (the parameter and the type) means you have combine both to get the actual info, which is non trivial and doesn't actually bring much in return.
But yes, it seems to be expected on a parameter, as the community seems to remain unaware of the type use annotations and annotated types in general.

**Comment by t1** [comment]
The `TYPE_USE` target makes sense by itself, but the `PARAMETER` target does, too. `@NonNull List<@NonNull String>` can be a valid parameter. I just had not expected that a) `TYPE_USE` makes the Java compiler accept the first `@NonNull`, too; and b) it still doesn't show up in reflection.

I'm at home at the user side, so I actually normally don't care too much about implementations; but why does this make implementation more difficult?

Otherwise, I understand that we all agree: we should add `PARAMETER`.

**Comment by kaqqao** [comment]
> it still doesn't show up in reflection

It does, just not on the parameter, but on it's `AnnotatedType`, e.g.

```java
method.getParameters[0].getAnnotatedType().getAnnotations()
```

or

```java
method.getAnnotatedParameterTypes[0].getAnnotations()
```

> but why does this make implementation more difficult?

Multiple sources of truth, nothing else.

> Otherwise, I understand that we all agree: we should add `PARAMETER`.

I guess so, yeah :)
