### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by t1** [eclipse/microprofile-graphql#227]
1. When a request is syntactically correct, but not semantically, a `Client Error` has to be raised from within the application; e.g. when a requested id can't be found. The spec is not clear about this.
1. Technical wrapper exceptions like `EJBException` should be unwrapped.
1. Add `@GraphQlWhitelist` to add the annotated exception to the [whitelist](https://download.eclipse.org/microprofile/microprofile-graphql-1.0.1/microprofile-graphql.html#_unchecked_exceptions). And for the symmetry's sake: `@GraphQlBlacklist` for the [blacklist](https://download.eclipse.org/microprofile/microprofile-graphql-1.0.1/microprofile-graphql.html#_checked_exceptions).
1. Document the `GraphQLException.ExceptionType` in the spec as well as the intended semantic of the values in the enum. Add more business related exception types: `NotFound`, `Forbidden`, `Invalid`.
1. Add an exception mapper mechanism, so the application can take full control.
1. [RFC-7807](https://tools.ietf.org/html/rfc7807) is a very well designed standard for RESTful services. Maybe we can evolve the error handling by learning from there:
a. Define a `type` extension field to contain a stable URI for the type of error, so clients can safely react on specific error types.
b. Define an `instance` extension field to contain a URI (e.g. a UUID-URN) that can be found in the logs.
c. If the `message` field is more like the `title`, a `detail` extension field could be added; or the other way around.
d. If these fields work out well, we could even upstream them to the GraphQL standard, so they become non-`extension` fields.

Maybe some of these points should go into a separate issue, but the discussion could start here ;-)

**Comment by phillip-kruger** [comment]
Hi @t1 - I like this. The `@GraphQlWhitelist` and `@GraphQlBlacklist` is a good idea. We keep the config options as well for exceptions out of control of the developer. 
For wrapped exceptions (like EJBException) - how would we know what exceptions to unwrap ? Config ?

**Comment by t1** [comment]
Everything should also be configurable, but I think the implementations should be smart enough to know about the most common use cases. Maybe it's also possible to look at all the causes and if _they_ are whitelisted, they should be unwrapped?

**Comment by phillip-kruger** [comment]
@t1 also look at #172

**Comment by t1** [comment]
I had seen #172... that's why I didn't add another point to add better support for partial results. This is even more important for the Client.

**Comment by phillip-kruger** [comment]
Cool ! :)

**Comment by phillip-kruger** [comment]
Can we break this up into smaller issues ?

**Comment by t1** [comment]
Yeah, I will break it up. Actually I didn't expect that there was so litte general need for discussion ;-)

**Comment by t1** [comment]
Split up into separate issues
