### ISSUE TITLE
How to provide a description to a type field?

### ISSUE THREAD

**Issue by jefrajames** [eclipse/microprofile-graphql#24]
Correct me if I'm wrong but it seems that there is no annotation to provide a description to a field type. @InputField enables that on Input Type but there is no equivalent on regular Type.

**Comment by kaqqao** [comment]
From the GraphQL point of view, all queries are output fields and vice versa, so the `@Query` annotation currently serves that purpose.

As mentioned in the last meeting, we might want to pull the description into its own `@Description` annotation (similar to `@DefaultValue`).

**Comment by andymc12** [comment]
Should we close this in favor of #44 ?

**Comment by phillip-kruger** [comment]
+1

**Comment by jefrajames** [comment]
OK let's close.
