### ISSUE TITLE
Project logo?

### ISSUE THREAD

**Issue by wtrocki** [eclipse/microprofile-graphql#245]
Hi

This is amazing project and I would like to help promoting it in blog posts and sample apps, however it is hard without logo. Is there any draft logo or something that can be used here?

**Comment by phillip-kruger** [comment]
I don't think any MicroProfile specs use their own logos ? Mostly just the MicroProfile logo ? @andymc12  ? (That does not mean we should not create one :) )

**Comment by wtrocki** [comment]
@phillip-kruger I can use GraphQL and Microprofile logo. Just feel that having this image in Readme will be much more welcoming etc. 

Something like this?
<img width="744" alt="Screenshot 2020-05-07 at 15 58 27" src="https://user-images.githubusercontent.com/981838/81310145-a44b5900-907b-11ea-9395-e6ba1b7e474c.png">

**Comment by andymc12** [comment]
I like combining the two logos - though I think that there should be a MicroProfile image file somewhere that includes a transparent background - that might make it look better next to the GraphQL logo with black or dark gray background.

Thanks @wtrocki for the promotion!  Please let us know when you have posted blog posts or samples, etc. - you can either let us know here (in this issue) or in [gitter](https://gitter.im/eclipse/microprofile-graphql) or in the [MP Google Group](https://groups.google.com/forum/#!forum/microprofile).

**Comment by phillip-kruger** [comment]
Can we close this ?
