### ISSUE TITLE
Specify http GET requests

### ISSUE THREAD

**Issue by t1** [eclipse/microprofile-graphql#258]
There should be a detailed description in the spec as well as appropriate tests in the TCK about how GET queries should look like exactly. According to [graphql.org](https://graphql.org/learn/serving-over-http/#get-request), they should look like this:

```
http://localhost:8080/superheroes/graphql?query={heroes{name}}
```

Additional query parameters for `variables` and `operationName` are optional.

**Comment by phillip-kruger** [comment]
Duplicate of #179 ?

**Comment by t1** [comment]
Sorry, I didn't see that. It's actually just a subset of #179, but we can proceed in the larger scope.
