### ISSUE TITLE
message field in error should be a wildcard

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#272]
When testing errors we should not have to match the message (just check that it's there? )

**Comment by t1** [comment]
maybe a regex? or disable in properties?

**Comment by phillip-kruger** [comment]
Disable in properties might work. Regex could still end up breaking an impl if the message of the underlying graphql-java change.

**Comment by tmiddlet2666** [comment]
@phillip-kruger I'm happy to take this one on as well as i've got about 8 tck tests failing as they have different error messages but fail for the correct reason.

**Comment by phillip-kruger** [comment]
Thanks @tmiddlet2666 !

**Comment by tmiddlet2666** [comment]
This is resolved by adding multiple output.json files to match the expected output.

**Comment by phillip-kruger** [comment]
Yes. Thanks @tmiddlet2666 !
