### ISSUE TITLE
Clarify spec: don't duplicate `Input` in the schema

### ISSUE THREAD

**Issue by t1** [eclipse/microprofile-graphql#285]
If an input parameter type already ends with `Input`, e.g. `SuperHeroInput`, the generated schema shouldn't repeat it to become `SuperHeroInputInput`.

This needs a small change to the text and a new test in the TCK.

**Comment by redmitry** [comment]
My question is why it adds "Input" to the @Input annotated and named type. This is weird!
We already have graphql with Spring and I am trying to pass to the microprofile. 
The schema is already defined and we have a lot of javascript code on the client side.
How can I define the input names?

Best,

D.

**Comment by phillip-kruger** [comment]
Maybe we can assume that when using `@Input` you are naming this uniquely and we should not apply the Input at the end. So we only do that if you have not used the annotation and we base it of the class name. If the name used in the annotation ends up not being unique we throw a RuntimeExeption maybe ?

**Comment by redmitry** [comment]
> Maybe we can assume that when using `@Input` you are naming this uniquely and we should not apply the Input at the end. So we only do that if you have not used the annotation and we base it of the class name. If the name used in the annotation ends up not being unique we throw a RuntimeExeption maybe ?

Although I don't understand why the same name can't be used as an input, this would definitely resolve my problem,
~~~java
@Type("Community")
@Input("CommunityFilters")
public class Community {...}
~~~
In the worst case, I would separate classes.

Thank you,

D.

**Comment by phillip-kruger** [comment]
Input and Types needs unique names. The example above we should create them as is and not append `Input` like we do currently.
The appending of `Input` came from when you do not name the class and it's used in both in- and output. But I think the spec need a change to only apply that if the name is not provided.

**Comment by redmitry** [comment]
To be fair, I do not see where the spec. says it should add "Input" when the @Input is explicitly defined.
On the other hand all examples and javadocs use "Input" endings:
~~~java
@Input("StarshipInput")
@Description("Input type for a starship")
public class Starship {
...
~~~
So it is probably more the implementation issue.

Anyway, thank you very much for the clarification.

Cheers,

D.

**Comment by phillip-kruger** [comment]
Are you talking about the server or client ?

**Comment by redmitry** [comment]
The server. In concrete:
https://www.wildfly.org/news/2020/08/13/Introducing-the-WildFly-GraphQL-feature-pack/
https://github.com/smallrye/smallrye-graphql

**Comment by phillip-kruger** [comment]
Ok, I'll have a look. Seems like I am confused and it should already work like I suggest. I'll get back to you

**Comment by phillip-kruger** [comment]
Hi. This is a bug in SmallRye. I think we can close here and I will fix it there. Thanks.
