### ISSUE TITLE
beans.xml in TCK library adds beans twice

### ISSUE THREAD

**Issue by tomas-langer** [eclipse/microprofile-graphql#290]
Hi, there is a `beans.xml` file in https://github.com/eclipse/microprofile-graphql/blob/master/server/tck/src/main/resources/META-INF/beans.xml

This marks the TCK library itself as a beans archive, which AFAIK is neither needed nor desired.

When you run the "container" under the same classloader as the test, this causes a duplicity of beans, as they are read both from this jar file and from the actual TCK test created through Arquillian.

Would it be possible to remove this file?

**Comment by phillip-kruger** [comment]
Yes sure ! Will you do a PR ?

**Comment by tomas-langer** [comment]
PR is fixed. I have ECA signed, I did not sign-off the commit.
