### ISSUE TITLE
Allow multiple input 

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#316]
Same as the change in output (#304) allow multiple input files.
At least one of the inputs needs to pass in order to pass the test.

**Comment by phillip-kruger** [comment]
@tmiddlet2666 - for some reason I can not assign you.

**Comment by tmiddlet2666** [comment]
ok thanks @phillip-kruger I'll take a look

**Comment by tmiddlet2666** [comment]
Thanks @phillip-kruger 
This should resolve some test failures i'm having related to https://github.com/eclipse/microprofile-graphql/issues/307
