### ISSUE TITLE
Alternative request format

### ISSUE THREAD

**Issue by t1** [eclipse/microprofile-graphql#342]
https://graphql.org/learn/serving-over-http/#post-request suggests to allow the query string to be part of the URL also for `POST` requests. It's not directly mentioned, but I guess this should also work for the `variables` URL parameter.

Maybe it would also make sense to allow all variables to be added directly as URL parameters, too, i.e. `https://superheroes.org/graphql?query=query+superHero($name:String!){superHero(name:$name){name}}&name=Wolverine`. I would not allow for mixing a `variables` parameter with direct parameters.

I'm not so sure about the second suggestion to support a `Content-Type` to be `application/graphql`, so the body directly contains the query.

**Comment by phillip-kruger** [comment]
Duplicate of https://github.com/eclipse/microprofile-graphql/issues/179 ?

**Comment by t1** [comment]
Yeah, this is a duplicate
