### ISSUE TITLE
Make `@Name` argument optional

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-graphql#384]
Just like what we do for RESTEasy and what JAX-RS should do in the future, you could make the argument of `@Name` optional and infer it from the method parameter name (if available) or the field or property it's on.

I guess the same can be said of other such annotations, including the header one, even though this one requires changing camel-case to HTTP-case.

Example:

```java
    @Query
    @Description("Get a Films from a galaxy far far away")
    public Film getFilm(@Name int filmId) {
        return service.getFilm(filmId);
    }
```

**Comment by FroMage** [comment]
Huh, wait, it appears the `@Name` annotation is optional, so probably this is not actually needed.

**Comment by phillip-kruger** [comment]
Yes, `@Name` is optional, it really is there if you want to name it different than the parameter name.

**Comment by FroMage** [comment]
OK thanks.

**Comment by phillip-kruger** [comment]
B.t.w for methods, the name will be derived from the method name, without the get/set/is.
