### ISSUE TITLE
Does mp-graphql support mp-metrics in openliberty ?

### ISSUE THREAD

**Issue by MastanaGuru** [eclipse/microprofile-graphql#396]
Hi 
I am running Open Liberty 21.0.0.8/wlp-1.0.55.cl210820210727-1323) on OpenJDK 64-Bit Server VM, version 11.0.7+10 with features mpGraphQL-1.0 and  mpMetrics-3.0 enabled but do not see graphql metrics in the /metrics endpoint.

Do we get metrics for mpGraphQL ?

**Comment by jmartisk** [comment]
The MP GraphQL spec does not describe any integration with metrics as of now, so this is a question that should be directed at OpenLiberty rather than MicroProfile - I'm not sure whether OpenLiberty has any support for this. I can only say that Quarkus does ;)

**Comment by andymc12** [comment]
@jmartisk is correct that the spec doesn't mention MP Metrics integration.  Open Liberty does support MP Metrics, but only at the 2.3 level.  Can you open an issue at https://github.com/OpenLiberty/open-liberty/issues for supporting MP Metrics 3.0? Thanks!
