### ISSUE TITLE
Support for jersey

### ISSUE THREAD

**Issue by vamshikrishnamraju** [eclipse/microprofile-graphql#403]
Hi

is there any implementation for jersey ?

Thanks

**Comment by andymc12** [comment]
Hi @vamshikrishnamraju - there is no Jersey-specific implementation.  I am only aware of two implementations that have passed the TCK: SmallRye and Helidon.  GraphQL SPQR may have also passed the TCK.  But none of these three implementations use Jersey. 

Jersey is a JAX-RS implementation that integrates with a web container (like Tomcat, Jetty, etc.) or a more full-fledge application server (like Open Liberty, Wildfly, etc.).  MP GraphQL implementations also integrate with web containers and app servers - they are built in to Open Liberty, Wildfly, Quarkus, and Helidon, but it should be possible to integrate MP GraphQL and an implementation into any Java application server so long as it supports CDI and MicroProfile Config.

Hope this helps!
