### ISSUE TITLE
Open Liberty 22.0.0.4-beta: MicroProfile GraphQL 2.0 Compatible Certification Request

### ISSUE THREAD

**Issue by WhiteCat22** [eclipse/microprofile-graphql#435]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  IBM
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty 22.0.0.4-beta](https://github.com/OpenLiberty/open-liberty/releases/tag/gm-22.0.0.4-beta)
- [x] Specification Name, Version and download URL:<br/>
  [MicroProfile GraphQL 2.0](https://github.com/eclipse/microprofile-graphql/releases/tag/2.0) 
- [x] Public URL of TCK Results Summary:<br/>
  https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java8-TCKResults.html
  https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java11-TCKResults.html
  https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java17-TCKResults.html
- [x] Java runtime used to run the implementation:<br/>
  Java 8, 11 and 17
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java8-TCKResults.html
  https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java11-TCKResults.html
  https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java17-TCKResults.html
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by Emily-Jiang** [comment]
done
