### ISSUE TITLE
@Description to move to it's own annotation

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#44]
As discussed in the meeting (https://docs.google.com/document/d/1gb3jirFGrJwDZSbrtnFPVTNjPNe3Y0dUYfm-HkU1c3U/edit#heading=h.4fgdpqwrqxep)

Move description field form annotations (eg. @Query @Mutation etc) to it's own Annotation. 
This way a InputField can also be described without an @Query annotation needed

**Comment by jefrajames** [comment]
I propose to define a new @FieldDescription annotation (that should be mapped on SPQR @Query under the cover). I'm going to do some tests ASAP to validate this option.

BTW, I have not been able to assign this issue to me.
