### ISSUE TITLE
@DefaultValue not working currently

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#46]
We need test cases for @DefaultValue. It does not seem to be working at the moment.

The schema still makes the field mandatory so you can not pass an empty value so that the default is being used

**Comment by andymc12** [comment]
@phillip-kruger I think this is working in OpenLiberty, but I will add a TCK test case to ensure it works.

**Comment by phillip-kruger** [comment]
Great ! Thanks
