### ISSUE TITLE
Document that fields are also queries

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-graphql#50]
Per conversation at [August 1st, 2019 hangout](https://docs.google.com/document/d/1gb3jirFGrJwDZSbrtnFPVTNjPNe3Y0dUYfm-HkU1c3U/edit#heading=h.xpx6vfxuho2d), we determined that we should document that each field on an entity is technically a query.  This allows for more complex and useful queries and field selection.  This should be documented in the spec.

**Comment by phillip-kruger** [comment]
Thanks !
