### ISSUE TITLE
enum is a keyword

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#6]
This error when you build the TCK:

**Enum:**
_microprofile-graphql/tck/src/main/java/org/eclipse/microprofile/graphql/tck/annotations/enum/package-info.java:[21,58] as of release 5, 'enum' is a keyword, and may not be used as an identifier_
and 
_microprofile-graphql/tck/src/main/java/org/eclipse/microprofile/graphql/tck/apps/annotations/enum/package-info.java:[21,58] as of release 5, 'enum' is a keyword, and may not be used as an identifier_

**Interface**
_microprofile-graphql/tck/src/main/java/org/eclipse/microprofile/graphql/tck/apps/annotations/interface/package-info.java:[21,58] <identifier> expected_
and
_microprofile-graphql/tck/src/main/java/org/eclipse/microprofile/graphql/tck/annotations/interface/package-info.java:[21,58] <identifier> expected_

I assume that means we need to name this differently ?

@WhiteCat22 ?

**Comment by WhiteCat22** [comment]
Weird, why would file paths cause these errors?

**Comment by phillip-kruger** [comment]
Yea I would not have thought that is a problem, but seems like it is. Not sure have we 'fix' it though ? Rename ?

**Comment by WhiteCat22** [comment]
I'll try playing around with it and see if I can figure something out. But you may be right.

What command were you using to build?

**Comment by phillip-kruger** [comment]
mvn clean install
But it also shows red in my IDE (Netbeans)
![image](https://user-images.githubusercontent.com/6836179/57088112-dfe17380-6d01-11e9-800f-9057c91004f4.png)

**Comment by WhiteCat22** [comment]
ahh, so it's a java issue. Enum is a java keyword so can't be in the package name. Makes sense now. Yeah, I'll have to rename them. Do you have any suggestions?

It would be nice to maintain consistency between all annotations however we decide to name the packages.

**Comment by phillip-kruger** [comment]
enum we can mayby write out (enumeration) , but not sure on interface. We can discuss tomorrow, as this might not be needed if we follow the dynamic route ?

**Comment by WhiteCat22** [comment]
enumeration is a good idea. I think it would still be a good idea to organize the tests into separate packages even if we go the dynamic route. We'd just have all the enum related graphql and json files in the enum package etc etc. Then it's not a big mess if anybody tries to look through the tck, everything is laid out neatly and logically.

**Comment by phillip-kruger** [comment]
Yes agree, but then it will not be java package so should be fine ?

**Comment by WhiteCat22** [comment]
Yes, as long as our solution doesn't have java files in the "packages" we should be fine. I just added package-infos.java to give a quick explanation of what tests go in each directory (and to have something in each directory so the structure would be tracked by Git).

I could convert the package-info.java files to a readme file in each directory instead. That way we preserver the file structure for organization, but don't blow up compiling java

**Comment by phillip-kruger** [comment]
Ok let's discuss tomorrow and update the issue with the outcome

**Comment by WhiteCat22** [comment]
sounds good

**Comment by phillip-kruger** [comment]
Fix by PR #8 Although this might be removed in when we do the dynamic tests as proposed.
