### ISSUE TITLE
How to specify whether a field is nullable or not

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-graphql#68]
In testing some JSON-B annotations, I noticed that all fields that used primitive (`long`, `int`, `boolean`, `float`, etc.) the schema made them all non-nullable (using the exclamation point in the schema - meaning that values for these fields _must_ be provided by the client).  If the Java field was annotated with `@DefaultValue(someValue)` then the primitive Java property was listed as nullable (no exclamation point).  

For all other (non-primitive) Java fields (`String`, `List`, `MyCustomWidget`, etc.) they were always nullable.  Looking at the SPQR code, there is a `@GraphQLNonNull` annotation that is used on Java fields, setters, etc. that would mark the field as non-nullable.  SPQR also honors `@javax.annotation.Nonnull` and some Bean Validation annotations (`@NotNull`, `@NotEmpty` and `@NotBlank`) and marks the field as non-nullable in the schema.

This issue exists to determine what we want to support in MP GraphQL and also to ensure that the behavior is documented correctly in the spec and tested correctly in the TCK.  It may also be used to add an API.

Here are some questions that we should answer first:
1) Should we have our own annotation for marking a field as non-nullable?  Something like `@org.eclipse.microprofile.graphql.NonNull`?
2) Should we also use JSON-B's `@JsonbNillable` (class level) and `@JsonbProperty(isNillable=true|false)` (setter/field level) to determine a field's nullable status?
3) Bean Validation is not part of the MicroProfile spec.  Should we honor those annotations?  Perhaps we could document them as "if the user or implementation uses Bean Validation, then these annotations would have the following effect..."
4) Is the behavior for primitives what we want?  (where a primitive is declared as non-nullable unless the Java property has a `@DefaultValue` annotation.)

Another alternative to 1 would be to add a boolean "isNullable" property to the `@InputField` annotation and then use that.  I personally would prefer to use a separate annotation, but this is still an option.

**Comment by kaqqao** [comment]
1. I'd say yes, purely because (I think) the user would expect it to be there...
2. This sounds reasonable... I was going to add this with Jackson to SPQR at some point
3. I'm working on kicking these out into a separate module in SPQR. I'd keep it out of the spec it depends on non MicroProfile specs. If the user wants it, they can enable the module...
4. This wasn't always the case in SPQR but sort of forced itself... Primitives in Java simply can't be null, so allowing them to be nullable in the schema creates a weird state. Anything with a default value must by definition be nullable (although the GraphQL spec is _seriously_ confusing on that point).

All this of course just my point of view, and open for debate.

**Comment by andymc12** [comment]
@kaqqao I agree with all your points except maybe 3:
> 3. I'm working on kicking these out into a separate module in SPQR. I'd keep it out of the spec it depends on non MicroProfile specs. If the user wants it, they can enable the module...

IIUC, if the user does have BeanValidation enabled in their environment, then any client that sent a null value for a `@NotNull`/`@NotBlank`/etc. field would get an error response.  So the field would be effectively non-nullable, but the schema would indicate that nulls were allowed.  Still... given that BeanValidation is not in MP, I think I could go either way on this issue.

**Comment by kaqqao** [comment]
The way I'm going to handle in SPQR for now is to detect the presence of BeanValidation on the class path and conditionally load the extra module. This works great, but can get into the limbo state when the app itself is loaded by one class loader and the BeanValidation itself by another (as you've already experienced with Jackson-specific module in SPQR that works the same way).

Service loader interface (as proposed by Philip) is a reliable approach, but requires the user to add a dependency explicitly. I'm really torn on this 😣

**Comment by andymc12** [comment]
@kaqqao I think that sounds like a good approach.  That should allow vendors like Liberty/Quarkus/etc. to explicitly enable the extra module if BeanValidation is available, but also avoid the overhead of checking for those annotations if BV is not available.

Thanks!

**Comment by phillip-kruger** [comment]
But bean validation is for validation ? Should we use it for marshalling ?

**Comment by andymc12** [comment]
@phillip-kruger true, my thinking was just that if validation was enabled, the behavior would ultimately be non-null anyway, so the schema might as well reflect that.

That said, it sounds like you and @kaqqao are both thinking that we shouldn't use BV annotations to determine the nullable status in the schema, so I'm fine with that.  If BV ever becomes a part of the MP spec, then we may want to change course.

**Comment by andymc12** [comment]
Looking into this a little more, I think I want to change my opinion on 2 (using JSON-B's `@JsonbNillable` and `@JsonbProperty(nillable=true|false)`).  The JSON-B default is for fields to not be nullable - so for serialization that means a null value is allowed, but then the field wouldn't be written to JSON - for de-serialization (which is what we need for conversion to input types) there doesn't seem to be any effect.  Also, the default JSON-B behavior is that types are "not-nillable", meaning that all GraphQL fields would end up being non-nullable unless the user explicitly marks the fields as nullable.  I think that is opposite of what we want - I think it makes more sense for all fields to nullable unless marked non-nullable.

So, I'm thinking that we should not look for JSON-B annotations when determining whether a field is nullable or not.  

Based on the conversation so far (and assuming everybody is ok with this comment), then here is how a field would be determined to be nullable or not:
1) Is the Java property a primitive?  If yes, does the Java property have a `@DefaultValue`?  If so, then it is nullable (takes the default value).  If not, then it is non-nullable.
2) Is the Java property's setter or field annotated with `@org.eclipse.microprofile.graphql.NonNullable` ? If so, then it is non-nullable.
3) The field is nullable.

Does that work for everybody?

Thanks again, Andy
