### ISSUE TITLE
More scalar types (Long, BigDecimal, Char etc)

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-graphql#81]
As @phillip-kruger mentioned in issue #80, graphql-java/SPQR defines a `Long` scalar type.  This should be documented in the spec, and tested in the TCK.

Currently the spec is incorrect (saying that Java `long`/`java.lang.Long` types are mapped to GraphQL `Int` scalars) - it says:

> Int - which maps to a Java int/Integer or long/Long.

This text should be changed when resolving this issue.

**Comment by phillip-kruger** [comment]
Some of the other that I have seen in graphql-java:

BigDecimal, BigInteger, Byte, Char , Short

I think it's reasonable to support those in the spec.

I was also thinking about Date (as in java.util.Date ??) even though LocalDate is supported, Should we not also support older Date and Calendar ?

**Comment by phillip-kruger** [comment]
Any thoughts on java.util.date ? and Calendar ? Also, any thoughts on allow users to define their own scalars ?

**Comment by phillip-kruger** [comment]
W.r.t the Date related scalars:
How will the date related scalars be serialized. Maybe configurable ? With default of ISO ?

**Comment by andymc12** [comment]
Here are my thoughts:
> BigDecimal, BigInteger, Byte, Char , Short

Yes, we should probably include these as built-in custom scalars.  

> Any thoughts on java.util.date ? and Calendar ? Also, any thoughts on allow users to define their own scalars ?

As far as the specification goes, I'd prefer to leave `java.util.Date`/`Calendar`/etc unspecified - meaning that implementations are free to use their own custom scalars for them.  We should probably advise users to use the `java.time.*` APIs for consistency.  

As for custom scalars, I was originally thinking that we would add that capability in the next release (tentatively 1.1). I think the spec would need to define some sort of interface for users to do their own serialization/validation of custom scalar Java types to strings and vice-versa - similar to `ParamConverter` in JAX-RS.   

We would also need some way to map Java types to custom scalars efficiently.  It's easy enough to create an `@Scalar("MyCustomScalar")` annotation, but there might be cases where users pull in third-party libraries and want to return types from those - maybe some sort of Eclipse Collection type or something - where they do not have the ability to add an annotation.  In such a case, we would need some other mechanism to map the type to a custom scalar.

> W.r.t the Date related scalars:
> How will the date related scalars be serialized. Maybe configurable ? With default of ISO ?

The serialization should be controlled by JSON-B - I think ISO is default for JSON-B, but users can override it with `@JsonbDateFormat(...)`.  Ultimately, they are serialized as a JSON string, i.e. "2019-10-24".

**Comment by phillip-kruger** [comment]
Ok cool. I am busy with the spec text and TCK changes for this. Will do a PR soon.

**Comment by phillip-kruger** [comment]
This is mostly done. Will remove String->char[] mapping in a next PR. Will close after that.

**Comment by phillip-kruger** [comment]
All done in PR #99 . Closing
