### ISSUE TITLE
@Id on non String / Primative

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#89]
[Phillip] what happens when @Id annotation is placed on a complex typed field?  
SPQR attempts to stringify the object, possibly to JSON.
Might be better to fail - deployment error (even for ints, floats, etc.)

**Comment by andymc12** [comment]
+1 we should document that `@Id` should only apply to `String` fields/methods.  I can work on that.

**Comment by phillip-kruger** [comment]
Should this not be String and some Primitives (and their Object classes) ? int, long ??

**Comment by phillip-kruger** [comment]
Fixed in #108
