### ISSUE TITLE
Move SuperHeroDatabase sample to TCK as a test app

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-graphql#9]
Per discussion on May 3, 2019 ([minutes](https://docs.google.com/document/d/1gb3jirFGrJwDZSbrtnFPVTNjPNe3Y0dUYfm-HkU1c3U/edit#bookmark=id.q5uu6bht73xq)), we decided to use the [SuperHeroDatabase sample](https://github.com/andymc12/SuperHeroDatabase) as one of the TCK test apps.

**Comment by phillip-kruger** [comment]
Fixed in PR #10

**Comment by phillip-kruger** [comment]
Closing
