### ISSUE TITLE
getX vs X

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#91]
What should we name the query in cases like @Query getX() ?  Should it be “getX” or “x”?
Possibly use a MP Config property to determine the behavior - default behavior should be “getX”.

**Comment by phillip-kruger** [comment]
Any feedback on the default behaviour? I think SPQR currently always remove the get, set, is. Maybe that is the default for the spec ? I am happy with that.

**Comment by andymc12** [comment]
Yes, I'm happy with that as well.  If that is the desired behavior, we should use this issue to update the spec document - I don't think that this behavior is currently documented in the spec text.

**Comment by phillip-kruger** [comment]
Thanks. Ok, I'll update the spec and double-check that we have tests for that.
