### ISSUE TITLE
Is @Name on argument mandatory

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#92]
Is Argument mandatory ? It should not allow no value.
Or we should have a way to name arguments without the annotation

**Comment by phillip-kruger** [comment]
Just use the compiled value ? arg1 arg2 etc.

**Comment by andymc12** [comment]
I lean toward making `@Argument` mandatory - that way it is clear which parameters are required in the query/mutation.

But I agree that the `@Argument` annotation should not allow no value.  This also forces the user to be intentional in the naming of the argument(s).

I prefer that we require users to explicitly name their arguments rather than generating "arg1", "arg2", etc.  as I think that will lead to better designed/documented apps.

**Comment by andymc12** [comment]
Yes, I think that makes sense.  I think that the spec should strongly recommend that users should name arguments using the `@SchemaName` (or whatever we end up calling it) annotation.

Another possibility that we discussed a while back was that if the user built their application the with `-parameters` compiler option, then the class byte code would retain the parameter names - allowing the implementation to use the actual parameter names (as opposed to `arg0`, `arg1`, etc.).  See https://www.logicbig.com/how-to/java-command/java-compile-with-method-parameter-names.html for more details.

Maybe the spec should just say that if there is no name defined by annotation, then the implementation will default to whatever `parameter.getName()` returns.  Wdyt?

**Comment by phillip-kruger** [comment]
Sounds good. Not sure if I can get that with Jandex, but that is more my problem than the spec's problem.

**Comment by phillip-kruger** [comment]
[Andy] I’m now leaning towards making it optional but then defaulting the names to parameter.getName().  In most cases that will be “arg0”, “arg1”, etc., but if the user compiles their app with the -parameters setting, then we might be able to get more meaningful parameter names.

So I'll double check that this is specified as above in the spec and add test cases.

**Comment by andymc12** [comment]
> So I'll double check that this is specified as above in the spec and add test cases.

Thanks!  I'm pretty sure that it is not documented like that - I think it basically says that the `@Argument` (now changing to `@SchemaName` or `@Name`, etc.) is required.

Note that the test case will either need to assume "arg0", "arg1", etc. or we will need to compile the test app with the `-parameters` compiler option.  Thanks again!

**Comment by phillip-kruger** [comment]
Now settled on `@Name`. I'll add the spec text for the above as discussed.

**Comment by andymc12** [comment]
Consensus from today's meeting was that `@Name` is not required for parameters (arguments), but it is strongly recommended as it is the only guaranteed portable way to ensure the argument names.

If a user compiles with `-parameters` option, then the implementation should try to use the Java parameter names as the schema argument names, but this is not a requirement.  Jandex-based implementations may still have trouble getting the parameter names even with the `-parameters` option.
